### PR TITLE
Fix regression with parsing of scalar value documents

### PR DESCRIPTION
**Pull request by tobil4sk**
This fixes a regression from 0f609dd314366858679a168933b03692699e8c6e where lua-simdjson switched to the ondemand parser. The ondemand::document type refuses to be convert to ondemand::value if the document is a single scalar value, e.g. `null`, `10`, `hello` or `true`.

It would give this error:
```
SCALAR_DOCUMENT_AS_VALUE: A JSON document made of a scalar (number, Boolean, null or string) is treated as a value. Use get_bool(), get_double(), etc. on the document instead.
```

I've also added relevant test cases.

### CODE REVIEW

**Comment by tobil4sk** [comment]
This solution seems like a bit of a hack, but it seems to be the way to have the least code changes in `luasimdjson.cpp`.

**Comment by FourierTransformer** [comment]
@tobil4sk How could it be less of a hack? My C++ isn't the best. I'm willing to dig in (or at least create an issue for the future) if you had any suggestions.

**Comment by tobil4sk** [comment]
I'm not sure there is another way of doing this at the moment, unless we just copy the function implementation to have one for documents and one for values, however, that is worse than using the template.

I've tried to look a bit into what other bindings are trying to do, though not many have switched to the ondemand parser yet. cysimdjson has a PR open which has duplicate implementations for document and value: https://github.com/TeskaLabs/cysimdjson/pull/13/files#diff-083a29ee978c1780e06e7653801bd953dfb9e92ce0ee95155534b51428f355a9. 

This might be something that could be improved on `simdjson`'s side, so maybe it is more useful to open an issue there.

**Comment by FourierTransformer** [comment]
Ahh I see. Well, I'll get this merged for now. I'll probably also update to 3.10.1 before cutting a new release.

**Comment by tobil4sk** [comment]
Thanks!

**Pull request merged**
