### PR TITLE
Reject invalid non-null tokens beginning with n

### PR DESCRIPTION
**Pull request by tobil4sk**
In 0f609dd314366858679a168933b03692699e8c6e, a regression was introduced where the parser would read any token that started with n as null.

The `.type()` method returns `json_type::null` simply if the token begins with `n`, and it does not check whether the token is actually valid.

Adding an `is_null()` call here ensures this and returns an error if the token starts with `n` but is not `null`. Calling `.value()` on the returned value will raise it as an exception if `is_null()` returned an error.

Currently with simdjson 3.10.1, there is a bug where calling `is_null` on a document object lacks this behaviour, so currently this patch only fixes the problem for non-scalar documents. See https://github.com/simdjson/simdjson/pull/2258

### CODE REVIEW

**Comment by FourierTransformer** [comment]
I'm thinking about waiting until the next release of simdjson before getting this merged. Alternatively commenting out the broken tests, and then we can enable them in the PR for the next simdjson release.

**Comment by tobil4sk** [comment]
> Alternatively commenting out the broken tests, and then we can enable them in the PR for the next simdjson release.

I've gone and commented those out, so the tests are passing for now. If you want to merge this now, I'll open a new PR so we don't forget about re-enabling them when the next simdjson version is released.

**Comment by FourierTransformer** [comment]
> I'll open a new PR so we don't forget about re-enabling them when the next simdjson version is released.

Sounds good to me! The only thing is whether or not to cut a release of lua-simdjson in the meanwhile.

**Comment by tobil4sk** [comment]
Thanks!

> Sounds good to me! The only thing is whether or not to cut a release of lua-simdjson in the meanwhile.

On second thought, it might be worth adding a workaround for now so that lua-simdjson still works properly and we don't have to wait until the next simdjson release. See #94

**Pull request merged**
